server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parish360
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false #default is set to true and warning occurs
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yml
#logging:
#  level:
#    org:
#      springframework:
#        security:
#          web:
#            FilterChainProxy: TRACE