server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/parish360
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false #default is set to true and warning occurs
logging:
  level:
    org:
      springframework:
        security:
          web:
            FilterChainProxy: TRACE